Instructable
Communicative CommsModule
Instructable(const int ChipSelect)
A constructor.
The Slave Select pin of the SPI peripheral in question.
bool issueCommand(mInstruct)
Issues a command to the peripheral.
Sends a command which is an element of the mInstruct type. mInstruct is the command issued to the peripheral. True if the peripheral acknowledges the command.
References Communicative::RequestReply, sCmd::Instruction, ACK.
Referenced by Sensor::StartMeasurement, Sensor::PauseMeasurementForMillis, Sensor::RestartMeasurement.
bool issueCommand(mInstruct, int)
Issues a command to the peripheral.
Sends a command which is an element of the mInstruct type qualified by an integer parameter (generally used to instruct on wait time or similar). mInstruct is the command issued to the peripheral and int is the integer qualifier. True if the peripheral acknowledges the command.
References Communicative::RequestReply, sCmd::Instruction, ACK.
bool issueCommand(mInstruct, float)
Issues a command to the peripheral.
Sends a command which is an element of the mInstruct type qualified by a float parameter. mInstruct is the command issued to the peripheral and float is the floating point qualifier. True if the peripheral acknowledges the command.
References Communicative::RequestReply, sCmd::Instruction, ACK.
bool issueCommand(mInstruct, int, float)
Issues a command to the peripheral.
Sends a command which is an element of the mInstruct type qualified by an integer parameter (generally used to instruct on wait time or similar) and a floating point parameter. mInstruct is the command issued to the peripheral, int is the integer qualifier and float is the floating point qualifier. True if the peripheral acknowledges the command.
References Communicative::RequestReply, sCmd::Instruction, ACK.
bool areYouConnected(void)
Checks to see whether the peripheral is connected.
Initiates handshake and nop transaction with the sensor to ensure that it is connected and responding appropriately. True if the peripheral is connected and communicating effectively.
References Communicative::isPeripheralConnected.