Communicative
int ChipSelect
Communicative(const int CS)
Constructor.
Constructor initialises the SS pin to be used in communications and initialises SPI as Master. CS is the Slave Select pin designation; most commonly PA4. SPISetup()
~Communicative(void)
Destructor.
Executes SPI.end();
bool isPeripheralConnected(void)
Checks whether Slave is connected.
Executes a nop transaction. true if handshake is successful and Slave responds to '?' with 'ACK' areYouAlive()
Referenced by Identifiable::Identifiable, Instructable::areYouConnected.
sCmd RequestReply(const mCmd)
Performs a complete transaction; expects Slave to Reply with sCmd object.
Executes a complete transaction: Clear SS -> Send '?' to slave -> recieve 'ACK' (0x06) from slave -> send request mCmd -> recieve sCmd -> set SS. mCmd is the mCmd object which constitutes the Request made to the slave. The sCmd object generated by the Slave as the reply to the request. RequestIdentity(), RequestData()
References REQUEST_DELAY_MICROS.
Referenced by DataSource::isThereData, Instructable::issueCommand, Instructor::howManyInstructions, Instructor::howLongShouldIWait, Instructor::loadNextCommand.
Identity RequestIdentity(const mCmd)
Performs a complete transaction; expects Slave to Reply with Identity object.
Executes a complete transaction: Clear SS -> Send '?' to slave -> recieve 'ACK' (0x06) from slave -> send request mCmd -> recieve Identity -> set SS. mCmd is the mCmd object which constitutes the Request made to the slave. The Idenity object generated by the Slave containing the Slave ID and name. RequestReply(), RequestData()
References REQUEST_DELAY_MICROS.
Referenced by Identifiable::hasIdentityChanged, Identifiable::updateIdentity.
Data RequestData(const mCmd)
Performs a complete transaction; expects Slave to Reply with a Data object.
Executes a complete transaction: Clear SS -> Send '?' to slave -> recieve 'ACK' (0x06) from slave -> send request mCmd -> recieve Data -> set SS. mCmd is the mCmd object which constitutes the Request made to the slave. The Data object generated by the Slave containing a two dimensional array of data points and the length, headings and units of the data array rows. RequestReply(), RequestIdentity()
References REQUEST_DELAY_MICROS.
Referenced by DataSource::loadData.
void SPISetup(void)
Initialises Master SPI.
Initialises SPI1 to {MSBFirst,Mode0,ClockDiv16} Communicative()
byte transferAndPause(const byte)
Fundamental byte transfer over SPI.
Executes SPI.transfer() and delays for a short time to allow Slave time to load reply into its Tx register as needed. byte is the 8 bit data packet to be sent to the Slave over MOSI the byte recieved from the slave over MISO RequestReply(), RequestData(),RequestIdentity()
unsigned int SPI_write(const T &value)
Template function to send an object of any type over SPI.
Sends any object over SPI by instantiating a pointer to the first byte of said object and then iterating said pointer through the memory domain of the object, for the size of objects of that type, calling transferAndPause() for each byte. NOTE: Requires the slave to be aware of the type of object to be recieved upon initiation of the communication, as the object must be reassembled, byte by byte, upon reception. value is the object of arbitrary type to be sent over SPI. zero if the function failes. transferAndPause()
unsigned int SPI_read(T &value)
Template function to recieve an object of any type over SPI.
Recieves any object over SPI by instantiating a pointer to the first byte of an object of the same type already instatiated in memory, and iterating through each byte of said object, overwriting each byte with the bytes recived over SPI from calls to transferAndPause(). NOTE: The type being recieved must be the same as the type of the local object. value is the object of arbitrary type which is being overwritten by the object of the same type being recieved. zero if the function failes. transferAndPause()
byte areYouAlive()
Executes a NOP transaction to check whether slave is connected.
Executes complete transaction but used a request which is ensured to not change Slave state and can thus be treated as a nop The byte send by the slave during the 'handshake' in reply to the '?' sent by master. RequestReply(), RequestData(),RequestIdentity()