Master
bool beginMeasurementYet
mCmd CurrentRequest
Identity ThisSensorID
Data MeasurementData
UserInstructions UserInstructionSet
Master(const int SensorIDNumber, const char SensorName[], const char InstructionSet[][SLAVE_COMMMAND_STRING_LENGTH], const int NumberOfInstructions, const sInstruct MasterInstructionSet[], const int intParams[], const float floatParams[])
References Identity::sensorID, Identity::sensorChipSelect, IDENTITY_SENSOR_NAME_LENGTH, Identity::SensorName, UserInstructions::NumOfInstructions, UserInstructions::InstructionCounter, UserInstructions::MasterInstructionSet, UserInstructions::iParams, UserInstructions::fParams, SLAVE_COMMMAND_STRING_LENGTH, UserInstructions::InstructionSet, Data::NumRows, NUMBER_OF_DATA_ROWS, Data::RowHeadings, Data::rowUnits, Data::NumColumns, DATA_ROW_LENGTH, Data::DataPoints.
Master(void)
~Master(void)
Master(volatile const Master &)
volatile Master& operator=(const Master &rhs) volatile
volatile Master& operator=(volatile const Master &rhs) volatile
void SETUP(const int SensorIDNumber, volatile char SensorName[], volatile char InstructionSet[][SLAVE_COMMMAND_STRING_LENGTH], const int NumberOfInstructions, volatile sInstruct MasterInstructionSet[], volatile int intParams[], volatile float floatParams[]) volatile
Set up of the commuication mechanism.
Intialised the auto-instantiated Master object, attaches the IRQ and sets up SPI communications. SensorIDNumber is the identity number of th slave. SensorName is the string name of the slave. InstructionSet is the array of strings associated with each instruction in the measuremnt cycle. Generally to be displayed to the user. NumberOfInstructions is the number of instructions in a single measurement cycle/procedure. MasterInstructionSet is the array of sInstruct objects associated with each instruction in the measurement cycle. Defines the required action by the master for each step of the measurement procedure. IntParams is the array of integer parameter associated with each instruction. FloatParams is the array of floating point parameters accosiated with each instruction.
References Identity::sensorID, Identity::sensorChipSelect, IDENTITY_SENSOR_NAME_LENGTH, Identity::SensorName, UserInstructions::NumOfInstructions, UserInstructions::InstructionCounter, UserInstructions::MasterInstructionSet, UserInstructions::iParams, UserInstructions::fParams, SLAVE_COMMMAND_STRING_LENGTH, UserInstructions::InstructionSet, Data::NumRows, NUMBER_OF_DATA_ROWS, Data::RowHeadings, Data::rowUnits, Data::NumColumns, DATA_ROW_LENGTH, Data::DataPoints, SPISetup.
void SPISetup(void) volatile
Sets up SPI and attaches interrupt.
References SPI1_NSS_PIN, SPI_IRQ.
Referenced by SETUP.
bool Handshake(void) volatile
Manages the handshake component of any transaction.
Manages the handshake between master and slave; defined by: Recieve '?' -> send 'ACK' (0x06). True if the handshake was successful.
Referenced by SPI_IRQ.
mCmd loadRequest(void) volatile
Retrieve the request sent by the master.
After each handshake, the master will proceed to send a request, defined by an mCmd object. This function must runafter each handshake. This function reassembles the mCmd request sent by the master, byte by byte and stores it in local memory. the mCmd object sent by the master.
Referenced by SPI_IRQ.
mInstruct getCurrentInstruction(void) volatile
Returns the mInstruct component of the most recently loaded request sent by the master.
References mCmd::Instruction.
int getCurrentInstructionIntParameter(void) volatile
Returns the integer parameter of the most recently loaded request sent by the master.
References mCmd::iParam.
float getCurrentInstructionFloatParameter(void) volatile
Returns the floating point parameter of the most recently loaded request sent by the master.
References mCmd::fParam.
void sendReply(const sCmd Reply) volatile
Send an sCmd object in reply to the request recieved from Master.
Referenced by sendTotalNumOfInstructions, sendNextUserInstruction, resendCurrentUserInstruction, beginMeasurement.
void sendReply(const sInstruct Instruction) volatile
Send a reply to the request recieved from master.
Assembles the sCmd object from the supplied parameters. Overloaded.
void sendReply(const sInstruct Instruction, volatile char InstructionString[SLAVE_COMMMAND_STRING_LENGTH]) volatile
Send a reply to the request recieved from master.
Assembles the sCmd object from the supplied parameters. Overloaded. Note the need for the char* to be defined locally as volatile char[]. Cannot pass string literals.
References SLAVE_COMMMAND_STRING_LENGTH, sCmd::sParam.
void sendReply(const sInstruct Instruction, const int iParam) volatile
Send a reply to the request recieved from master.
Assembles the sCmd object from the supplied parameters. Overloaded.
void sendReply(const sInstruct Instruction, const float fParam) volatile
Send a reply to the request recieved from master.
Assembles the sCmd object from the supplied parameters. Overloaded.
void sendReply(const sInstruct Instruction, const int iParam, const int fParam) volatile
Send a reply to the request recieved from master.
Assembles the sCmd object from the supplied parameters. Overloaded.
void sendReply(sInstruct Instruction, int iParam, volatile char InstructionString[SLAVE_COMMMAND_STRING_LENGTH]) volatile
Send a reply to the request recieved from master.
Assembles the sCmd object from the supplied parameters. Overloaded. Note the need for the char* to be defined locally as volatile char[]. Cannot pass string literals.
References SLAVE_COMMMAND_STRING_LENGTH, sCmd::sParam.
void sendReply(sInstruct Instruction, float fParam, volatile char InstructionString[SLAVE_COMMMAND_STRING_LENGTH]) volatile
Send a reply to the request recieved from master.
Assembles the sCmd object from the supplied parameters. Overloaded. Note the need for the char* to be defined locally as volatile char[]. Cannot pass string literals.
References SLAVE_COMMMAND_STRING_LENGTH, sCmd::sParam.
void sendReply(sInstruct Instruction, int iParam, float fParam, volatile char InstructionString[SLAVE_COMMMAND_STRING_LENGTH]) volatile
Send a reply to the request recieved from master.
Assembles the sCmd object from the supplied parameters. Overloaded. Note the need for the char* to be defined locally as volatile char[]. Cannot pass string literals.
References SLAVE_COMMMAND_STRING_LENGTH, sCmd::sParam.
void sendData(void) volatile
Sends the local Data object to the master in reply to appropriate request.
Sends Data object to the master in reponse to a request made by the master for Data. NOTE: This must be used as the response to the appropriate mInstruct request. In paricular, (mInstruct)SendDataPlease
void sendIdentity(void) volatile
Sends slave Identity object to the master in reply to appropriate request.
Sends the slave Identity object in response to an appropriate request made by master. NOTE: This must be used as the response to the appropriate mInstruct request. In paricular, (mInstruct)WhoAreYou
bool PushMeasurementVector(const MeasurementVectors VectorNumber, const float Measurement) volatile
Pushes a data point onto one of the data vectors.
Adds a data point to the next available slot in a particular vector until the vector (row) in the data array is full. VectorNumber is the enumerated reference to the row/vector in the data array being accessed. Measurement is the data point to be stored. False if the vector/row in question is full. (See DATA_ROW_LENGTH).
References First, Data::NumColumns, DATA_ROW_LENGTH, Data::DataPoints, Second, Third.
bool PopMeasurementVector(MeasurementVectors VectorNumber) volatile
Pops a data point from the tail end of a designated vector.
Removes the most recent data point from the vector in question by marking said data slot writeable to be the next PushMeasurementVector(). VectorNumber is the enumerated reference to the row/vector in the data array being accessed. False if the vector/row in question is empty.
References First, Data::NumColumns, Second, Third.
void ClearMeasurementVector(MeasurementVectors VectorNumber) volatile
Clears all data points from a particular vector.
VectorNumber is the enumerated reference to the row/vector in the data array being accessed.
References First, Data::NumColumns, Second, Third.
void setMeasurementVectorHeading(MeasurementVectors VectorNumber, volatile char Heading[ROW_HEADING_LENGTH]) volatile
Sets the string heading assigned to a paritcular data vector.
NOTE: The Heading parameter must be declared locally as volatile char[]. Literal strings cannot be passed to this function. VectorNumber is the enumerated reference to the row/vector in the data array in question. Heading[] is the character array containing the string heading.
References First, ROW_HEADING_LENGTH, Data::RowHeadings, Second, Third.
void setMeasurementVectorUnits(MeasurementVectors VectorNumber, volatile char Units[ROW_UNIT_LENGTH]) volatile
Sets the string Units assigned to a paritcular data vector.
NOTE: The Units parameter must be declared locally as volatile char[]. Literal strings cannot be passed to this function. VectorNumber is the enumerated reference to the row/vector in the data array in question. Units[] is the character array containing the string heading.
References First, ROW_UNIT_LENGTH, Data::rowUnits, Second, Third.
bool isThereData(void) volatile
Checks to see whether any data has been pushed to any of the data vectors locally.
True if any data points exist in the data vectors locally.
References Data::NumColumns, First, Second, Third.
void sendTotalNumOfInstructions(void) volatile
Sends a reply to Master specifiying the total number of instructions in a measurement procedure.
References sendReply, ReferToInt, UserInstructions::NumOfInstructions.
int getCurrentInstructionNumber(void) volatile
Gets the value of the counter which tracks the current instruction number throughout the measurement procedure.
References UserInstructions::InstructionCounter.
bool sendNextUserInstruction(void) volatile
Sends the next instruction in the measurement cycle to the master.
Sends the next instruction in the measurement cycle array in reponse to the appropriate request from master. Specifically, (mInstruct)NextCommandPlease. This method will auto-advance the measurement cycle to the next instruction and re-define the 'current instruction'. False if the final instruction in the measurement procedure has already been sent and the measurement procedure is now complete.
References UserInstructions::InstructionCounter, UserInstructions::NumOfInstructions, sendReply, UserInstructions::MasterInstructionSet, UserInstructions::iParams, UserInstructions::fParams, UserInstructions::InstructionSet.
void resendCurrentUserInstruction(void) volatile
Resends the cuurent instruction in the measurement procedure to the master.
This method will NOT advance the measurement cycle.
References UserInstructions::InstructionCounter, sendReply, UserInstructions::MasterInstructionSet, UserInstructions::iParams, UserInstructions::fParams, UserInstructions::InstructionSet.
void restartUserInstructionCycle(void) volatile
Restarts the measurement prcedure.
Restarts the measuement procedure such that the next instruction sent will be the first instruction in the measurement cycle.
References UserInstructions::InstructionCounter.
void beginMeasurement(void) volatile
Updates state to indicate that Master has requested the intitiation of the measurement procedure.
Designed to allow the IRQ to update the slave state so that the procedural code in main() can initiate the measurement procedure.
References SensorMaster, sendReply, ACK.
bool shallIStart(void) volatile
Checks whether the beginMeasurement() method has been called.
Allows procedural code in main() to determine whether the system state has changed during an interrupt in response to a request by the master to initiate the measurement procedure.
unsigned int SPI_write(const T &value) volatile
unsigned int SPI_read(T &value) volatile