.TH "Communicative.h" 3 "Mon Aug 12 2019" "OOPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Communicative.h
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'SPI_InstructionSet\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCommunicative\fP"
.br
.RI "A class to manage communication with slave module\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OOPI from the source code\&.
