.TH "Communicative" 3 "Mon Aug 12 2019" "OOPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Communicative \- A class to manage communication with slave module\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Communicative\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommunicative\fP (const int CS)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fB~Communicative\fP (void)"
.br
.RI "Destructor\&. "
.ti -1c
.RI "bool \fBisPeripheralConnected\fP (void)"
.br
.RI "Checks whether Slave is connected\&. "
.ti -1c
.RI "\fBsCmd\fP \fBRequestReply\fP (const \fBmCmd\fP)"
.br
.RI "Performs a complete transaction; expects Slave to Reply with \fBsCmd\fP object\&. "
.ti -1c
.RI "\fBIdentity\fP \fBRequestIdentity\fP (const \fBmCmd\fP)"
.br
.RI "Performs a complete transaction; expects Slave to Reply with \fBIdentity\fP object\&. "
.ti -1c
.RI "\fBData\fP \fBRequestData\fP (const \fBmCmd\fP)"
.br
.RI "Performs a complete transaction; expects Slave to Reply with a \fBData\fP object\&. "
.in -1c
.SH "Detailed Description"
.PP 
A class to manage communication with slave module\&. 

This class is designed for SPI communication with a slave device\&. The class responsibilities include both SPI initialisation and fundamental transactions\&. The transaction protocol implemented follows the following flow: Clear SS -> Send '?' to slave -> recieve 'ACK' (0x06) from slave -> send request \fBmCmd\fP -> recieve sCmd/Data/Identity as expected -> set SS\&. Where \fBmCmd\fP, \fBsCmd\fP, \fBData\fP and \fBIdentity\fP are structures defined as types\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBCommunicative\fP (const int CS)"

.PP
Constructor\&. Constructor initialises the SS pin to be used in communications and initialises SPI as \fBMaster\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fICS\fP is the Slave Select pin designation; most commonly PA4\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
SPISetup() 
.RE
.PP

.SS "~\fBCommunicative\fP (void)"

.PP
Destructor\&. Executes SPI\&.end(); 
.SH "Member Function Documentation"
.PP 
.SS "bool isPeripheralConnected (void)"

.PP
Checks whether Slave is connected\&. Executes a nop transaction\&. 
.PP
\fBReturns:\fP
.RS 4
true if handshake is successful and Slave responds to '?' with 'ACK' 
.RE
.PP
\fBSee also:\fP
.RS 4
areYouAlive() 
.RE
.PP

.SS "\fBData\fP RequestData (const \fBmCmd\fP Request)"

.PP
Performs a complete transaction; expects Slave to Reply with a \fBData\fP object\&. Executes a complete transaction: Clear SS -> Send '?' to slave -> recieve 'ACK' (0x06) from slave -> send request \fBmCmd\fP -> recieve \fBData\fP -> set SS\&. 
.PP
\fBParameters:\fP
.RS 4
\fI\fBmCmd\fP\fP is the \fBmCmd\fP object which constitutes the Request made to the slave\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The \fBData\fP object generated by the Slave containing a two dimensional array of data points and the length, headings and units of the data array rows\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRequestReply()\fP, \fBRequestIdentity()\fP 
.RE
.PP

.SS "\fBIdentity\fP RequestIdentity (const \fBmCmd\fP Request)"

.PP
Performs a complete transaction; expects Slave to Reply with \fBIdentity\fP object\&. Executes a complete transaction: Clear SS -> Send '?' to slave -> recieve 'ACK' (0x06) from slave -> send request \fBmCmd\fP -> recieve \fBIdentity\fP -> set SS\&. 
.PP
\fBParameters:\fP
.RS 4
\fI\fBmCmd\fP\fP is the \fBmCmd\fP object which constitutes the Request made to the slave\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The Idenity object generated by the Slave containing the Slave ID and name\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRequestReply()\fP, \fBRequestData()\fP 
.RE
.PP

.SS "\fBsCmd\fP RequestReply (const \fBmCmd\fP Request)"

.PP
Performs a complete transaction; expects Slave to Reply with \fBsCmd\fP object\&. Executes a complete transaction: Clear SS -> Send '?' to slave -> recieve 'ACK' (0x06) from slave -> send request \fBmCmd\fP -> recieve \fBsCmd\fP -> set SS\&. 
.PP
\fBParameters:\fP
.RS 4
\fI\fBmCmd\fP\fP is the \fBmCmd\fP object which constitutes the Request made to the slave\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
The \fBsCmd\fP object generated by the Slave as the reply to the request\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBRequestIdentity()\fP, \fBRequestData()\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for OOPI from the source code\&.
