.TH "DataSource.h" 3 "Mon Aug 12 2019" "OOPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataSource.h
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'SPI_InstructionSet\&.h'\fP
.br
\fC#include 'Instructable\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDataSource\fP"
.br
.RI "A class which models a Sensor/peripheral as an entity which is a source of data\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OOPI from the source code\&.
