.TH "Identifiable.cpp" 3 "Mon Aug 12 2019" "OOPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Identifiable.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'Identifiable\&.h'\fP
.br
\fC#include 'SPI_InstructionSet\&.h'\fP
.br
\fC#include <SPI\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OOPI from the source code\&.
