.TH "Sensor.cpp" 3 "Mon Aug 12 2019" "OOPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'DataSource\&.h'\fP
.br
\fC#include 'Instructor\&.h'\fP
.br
\fC#include 'Instructable\&.h'\fP
.br
\fC#include 'Identifiable\&.h'\fP
.br
\fC#include 'Sensor\&.h'\fP
.br
\fC#include 'SPI_InstructionSet\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OOPI from the source code\&.
