.TH "Sensor.h" 3 "Mon Aug 12 2019" "OOPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sensor.h
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'SPI_InstructionSet\&.h'\fP
.br
\fC#include 'Instructor\&.h'\fP
.br
\fC#include 'DataSource\&.h'\fP
.br
\fC#include 'Instructable\&.h'\fP
.br
\fC#include 'Identifiable\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSensor\fP"
.br
.RI "A class which models a Sensor/peripheral\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for OOPI from the source code\&.
